### ISSUE TITLE
Unable to generate seed

### ISSUE THREAD

**Issue by KokiriHylian** [PhlexPlexico/mm3dr#81]
During the "Placing Items" stage when generating a seed, receiving the message "Failed to generate after 5 tries." I'm not sure if this is due to the settings I have, but it's been happening consistently since version v1.1 of the Randomizer. Before v1.1, I was able to generate without issue using the same settings.

This latest attempt was on v1.2.1-d664f0. The seed number shown after the failed attempt was 1455388369.

![image](https://github.com/PhlexPlexico/mm3dr/assets/142831054/2b359961-bb02-4f59-8fc6-afaf20b65bb2)
![image](https://github.com/PhlexPlexico/mm3dr/assets/142831054/20b82893-feac-4c30-bb3a-b94ddc807100)

**Comment by PhlexPlexico** [comment]
Hi,

This is because there was a bunch of logic errors within the generator app before version 1.2. Since there is logic that now calculates if a play through is complete-able. Please adjust some of your settings to see if you can get a run to generate. Also, this is not the repo to report issues for logic, I would recommend going here to report issues in regards to placement logic - https://github.com/Z3DR/MM3D_Randomizer/issues

Thanks!

**Comment by KokiriHylian** [comment]
Ok, sounds good. I had to reduce the amount of excluded locations until it worked. Thanks!
